os: osx
osx_image: xcode10.1

# Command to install dependencies
install:
  - ./.travis-install-dependencies.sh

# Command to run tests
script:
  - ./runtests.sh

# Defines the branches on which the tests are run on
branches:
  only:
  - master
  - development
